### ISSUE TITLE
Delay required for scan to work

### ISSUE THREAD

**Issue by StefanoSperetta** [DelfiSpace/I2CScanner#1]
A 5ms delay is needed to ensure the scan function works: this delay may mask some timing issue in the code and should be removed ASAP by solving the underlying timing issue.

**Comment by johcarvajal** [comment]
Is this timing issue due to specific driver implementation?

**Comment by StefanoSperetta** [comment]
I think it is due to DWire (and Wire before it). The problem for me is that after requestFrom returned, all the operations related to I2C should have concluded and a new I2C transaction can start. 

Interestingly enough, on Friday this was an issue and I just recompiled and the issue disappeared....

But the bus sometimes locks up anyway... There is probably a timing issue (and this scares me a lot since it's locking the whole CPU).

**Comment by StefanoSperetta** [comment]
Problem solved. The problem was related to DWire and is is fixed in issue11 branch. Write and requestFrom were accessing the I2C controller before the previous transaction was completely over.
